change

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -17,7 +17,9 @@ jobs:
         env:
           AQUA_KEY: ${{ secrets.AQUA_KEY }}
           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          TRIVY_RUN_AS_PLUGIN: 'aqua'
+          CSPM_URL: https://stage.api.cloudsploit.com
+          AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com/v2/build
+          TRIVY_RUN_AS_PLUGIN: "aqua"
       - name: Sensitive file modification
         run: echo "modification made" >> sensitive_file
       - name: Login to DockerHub
@@ -28,27 +30,26 @@ jobs:
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v3
         with:
-           # Path to SARIF file relative to the root of the repository
+          # Path to SARIF file relative to the root of the repository
           sarif_file: results.sarif
           category: trivy
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          push: true
-          tags: "saargondocker/graphql-vuln:${{github.branch}}-${{ github.sha }}"
-      - name: Manifest Generation
-        run: |
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | shasum -a 256 ; then
-            echo "install.sh checksum failed"
-            exit 1
-          fi
-          sh install.sh
-          rm install.sh install.sh.checksum
-          billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-              --aqua-key "${{ secrets.AQUA_KEY }}" \
-              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-              --artifact-path "saargondocker/graphql-vuln:${{github.branch}}-${{ github.sha }}"
-
+      # - name: Build and push
+      #   uses: docker/build-push-action@v3
+      #   with:
+      #     push: true
+      #     tags: "saargondocker/graphql-vuln:${{github.branch}}-${{ github.sha }}"
+      # - name: Manifest Generation
+      #   run: |
+      #     curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+      #     curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+      #     if ! cat install.sh.checksum | shasum -a 256 ; then
+      #       echo "install.sh checksum failed"
+      #       exit 1
+      #     fi
+      #     sh install.sh
+      #     rm install.sh install.sh.checksum
+      #     billy generate \
+      #         --access-token "${{ secrets.GITHUB_TOKEN }}" \
+      #         --aqua-key "${{ secrets.AQUA_KEY }}" \
+      #         --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+      #         --artifact-path "saargondocker/graphql-vuln:${{github.branch}}-${{ github.sha }}"
